import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// // src/app/layout.tsx
// import React from 'react';
// import { ThemeProvider, CssBaseline } from '@mui/material';
// // import theme from '../theme'; // Certifique-se de que o caminho está correto

// const Layout = ({ children }: { children: React.ReactNode }) => {
//   return (
//     // <ThemeProvider theme={theme}>
//       <CssBaseline />
//       {children}
//     // </ThemeProvider>
//   );
// };

// export default Layout;

